import {
  AcademicCapIcon,
  ArrowPathIcon,
  ArrowPathRoundedSquareIcon,
  Bars3Icon,
  ArrowRightOnRectangleIcon,
  ArrowTrendingDownIcon,
  ArrowsRightLeftIcon,
  BellAlertIcon,
  BoltIcon,
  BookOpenIcon,
  BriefcaseIcon,
  BuildingLibraryIcon,
  BuildingOffice2Icon,
  CalendarDaysIcon,
  CameraIcon,
  ChartBarIcon,
  ChartBarSquareIcon,
  ChatBubbleLeftRightIcon,
  CheckCircleIcon,
  CheckIcon,
  ClipboardDocumentListIcon,
  ClockIcon,
  CloudIcon,
  Cog6ToothIcon,
  CpuChipIcon,
  CubeIcon,
  CursorArrowRaysIcon,
  DevicePhoneMobileIcon,
  DocumentTextIcon,
  EnvelopeIcon,
  FaceFrownIcon,
  FolderIcon,
  GlobeAltIcon,
  HeartIcon,
  InboxIcon,
  KeyIcon,
  LifebuoyIcon,
  LightBulbIcon,
  LinkIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MapIcon,
  MegaphoneIcon,
  PencilSquareIcon,
  PlayIcon,
  PuzzlePieceIcon,
  RocketLaunchIcon,
  ScaleIcon,
  ShoppingCartIcon,
  SparklesIcon,
  UserGroupIcon,
  UserIcon,
  WrenchScrewdriverIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";
import {
  CheckCircleIcon as CheckCircleSolidIcon,
  CheckIcon as CheckSolidIcon,
  ChatBubbleLeftEllipsisIcon as ChatSolidIcon,
} from "@heroicons/react/24/solid";

const OUTLINE_ICONS = {
  "academic-cap": AcademicCapIcon,
  "arrow-path": ArrowPathIcon,
  "arrow-path-rounded": ArrowPathRoundedSquareIcon,
  "bars-3": Bars3Icon,
  "arrow-right-on-rectangle": ArrowRightOnRectangleIcon,
  "arrow-trending-down": ArrowTrendingDownIcon,
  "arrows-right-left": ArrowsRightLeftIcon,
  "bell-alert": BellAlertIcon,
  bolt: BoltIcon,
  "book-open": BookOpenIcon,
  briefcase: BriefcaseIcon,
  "building-library": BuildingLibraryIcon,
  "building-office": BuildingOffice2Icon,
  "calendar-days": CalendarDaysIcon,
  camera: CameraIcon,
  "chart-bar": ChartBarIcon,
  "chart-bar-square": ChartBarSquareIcon,
  "chat-bubble": ChatBubbleLeftRightIcon,
  "check-circle": CheckCircleIcon,
  check: CheckIcon,
  "clipboard-list": ClipboardDocumentListIcon,
  clock: ClockIcon,
  cloud: CloudIcon,
  cog: Cog6ToothIcon,
  "cpu-chip": CpuChipIcon,
  cube: CubeIcon,
  "cursor-arrow-rays": CursorArrowRaysIcon,
  "device-mobile": DevicePhoneMobileIcon,
  "document-text": DocumentTextIcon,
  envelope: EnvelopeIcon,
  "face-frown": FaceFrownIcon,
  folder: FolderIcon,
  "globe-alt": GlobeAltIcon,
  heart: HeartIcon,
  inbox: InboxIcon,
  key: KeyIcon,
  lifebuoy: LifebuoyIcon,
  "light-bulb": LightBulbIcon,
  link: LinkIcon,
  "lock-closed": LockClosedIcon,
  "magnifying-glass": MagnifyingGlassIcon,
  map: MapIcon,
  megaphone: MegaphoneIcon,
  "pencil-square": PencilSquareIcon,
  play: PlayIcon,
  puzzle: PuzzlePieceIcon,
  "rocket-launch": RocketLaunchIcon,
  ruler: ScaleIcon,
  "shopping-cart": ShoppingCartIcon,
  sparkles: SparklesIcon,
  "user-group": UserGroupIcon,
  user: UserIcon,
  wrench: WrenchScrewdriverIcon,
  xmark: XMarkIcon,
};

const SOLID_ICONS = {
  "check-circle": CheckCircleSolidIcon,
  check: CheckSolidIcon,
  "chat-bubble": ChatSolidIcon,
};

export default function Icon({
  name,
  className = "w-5 h-5",
  solid = false,
  ...props
}) {
  const registry = solid ? { ...OUTLINE_ICONS, ...SOLID_ICONS } : OUTLINE_ICONS;
  const Component = registry[name];
  if (!Component) return null;
  return <Component className={className} aria-hidden {...props} />;
}

export function CheckMark({ className = "w-4 h-4 text-green" }) {
  return <CheckSolidIcon className={className} aria-hidden />;
}
